# Generated by Django 3.1.5 on 2021-01-27 15:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Enter news title', max_length=100)),
                ('text', tinymce.models.HTMLField(help_text='Enter news text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('pre', 'pre_moderation'), ('act', 'active'), ('arc', 'in_the_archive')], default='pre', help_text='Select news status', max_length=3)),
                ('images', models.ManyToManyField(blank=True, null=True, to='newsline.Image')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
